
syncerplus:
  redispool:
    #池中空闲链接回收线程执行间隔时间  例：每隔1000毫秒执行一次回收函数
    timeBetweenEvictionRunsMillis: 200
    #池中空闲连接回收未使用的时间  例：1800000毫秒未使用则回收  默认值是30分钟。1800000
    idleTimeRunsMillis: 100000
    #最小池大小
    minPoolSize: 3
    #最大池大小
    maxPoolSize: 10
    #连接超时时间
    maxWaitTime: 10000

  poolconfig:
    #核心池大小
    corePoolSize: 100
    #最大池大小
    maxPoolSize: 1500
    #队列最大长度
    queueCapacity: 1600
    #线程池维护线程所允许的空闲时间
    keepAliveSeconds: 300

#logging:
server:
  port: 8080
#  config: log/logback.xml
#logging:
#  config: config/logback.xml

logging:

  level:
    root: INFO
#syncer配置以及数据文件存路径路径配置



syncer:
  config:
    auth: true
    swagger: false
    path:
      logfile: ./log
      datafile: ./


info:
  app:
    name: redis syncer
    version: 3.0.1
    description: redis数据同步服务

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/syncer.db
#    url: jdbc:sqlite:D:\github\redissyncer-service\data\syncer.db
    username:
    password:

    hikari:
      maximum-pool-size: 3
      connection-timeout: 300000
      minimum-idle: 1

  application:
    name: test-thymelead
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
#    schema: classpath:init.sql
#    initialization-mode: ALWAYS
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
    jmx:
      exposure:
        include:
  endpoint:
    health:
      #显示详细信息
      show-details: always







