syncerplus:
  redispool:
    #池中空闲链接回收线程执行间隔时间  例：每隔1000毫秒执行一次回收函数
    timeBetweenEvictionRunsMillis: 300000
    #池中空闲连接回收未使用的时间  例：1800000毫秒未使用则回收  默认值是30分钟。
    idleTimeRunsMillis: 1800000
    #最小池大小
    minPoolSize: 1
    #最大池大小
    maxPoolSize: 25
    #连接超时时间
    maxWaitTime: 2000
